"""resume uploads database

Revision ID: 7d6424e0a6df
Revises: 9e8b15fe9e03
Create Date: 2025-02-28 06:54:10.456027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6424e0a6df'
down_revision: Union[str, None] = '9e8b15fe9e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('minio_resume_id', sa.UUID(), nullable=False),
    sa.Column('mongodb_resume_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'users', 'resume_uploads', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('resume_uploads')
    # ### end Alembic commands ###
